### ISSUE TITLE
reddit.py: TypeError: Invalid URL or no posts exist

### ISSUE THREAD

**Issue by juanpabloaj** [juanpabloaj/entries-by-votes#1]
```
ERROR:tornado.application:Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x7efed01fb8c8>, <tornado.concurrent.Future object at 0x7efed01e0c18>)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/praw/reddit.py", line 413, in info
    self.get(API_PATH['info'], params=params)]
  File "/usr/local/lib/python3.6/site-packages/praw/reddit.py", line 367, in get
    data = self.request('GET', path, params=params)
  File "/usr/local/lib/python3.6/site-packages/praw/reddit.py", line 472, in request
    params=params)
  File "/usr/local/lib/python3.6/site-packages/prawcore/sessions.py", line 179, in request
    params=params, url=url)
  File "/usr/local/lib/python3.6/site-packages/prawcore/sessions.py", line 110, in _request_with_retries
    data, files, json, method, params, retries, url)
  File "/usr/local/lib/python3.6/site-packages/prawcore/sessions.py", line 95, in _make_request
    params=params)
  File "/usr/local/lib/python3.6/site-packages/prawcore/rate_limit.py", line 32, in call
    kwargs['headers'] = set_header_callback()
  File "/usr/local/lib/python3.6/site-packages/prawcore/sessions.py", line 139, in _set_header_callback
    self._authorizer.refresh()
  File "/usr/local/lib/python3.6/site-packages/prawcore/auth.py", line 299, in refresh
    self._request_token(grant_type='client_credentials')
  File "/usr/local/lib/python3.6/site-packages/prawcore/auth.py", line 138, in _request_token
    response = self._authenticator._post(url, **data)
  File "/usr/local/lib/python3.6/site-packages/prawcore/auth.py", line 31, in _post
    raise ResponseException(response)
prawcore.exceptions.ResponseException: received 503 HTTP response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/tornado/ioloop.py", line 605, in _run_callback
    ret = callback()
  File "/usr/local/lib/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tornado/ioloop.py", line 626, in _discard_future_result
    future.result()
  File "/usr/local/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/usr/local/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/src/app/entries/get_entries.py", line 70, in entries_consumer
    votes = yield votes_from_entry(link)
  File "/usr/local/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/usr/local/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/usr/local/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/src/app/entries/get_entries.py", line 54, in votes_from_entry
    for vote in (yield votes_from_reddit(link)):
  File "/usr/local/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/usr/local/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/usr/local/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/src/app/entries/get_entries.py", line 45, in votes_from_reddit
    return (yield thread_pool.submit(Reddit().votes_and_comments, url))
  File "/usr/local/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 398, in result
    return self.__get_result()
  File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/app/entries/__init__.py", line 182, in votes_and_comments
    for sub in self.client.info(url=url):
  File "/usr/local/lib/python3.6/site-packages/praw/reddit.py", line 416, in info
    raise TypeError('Invalid URL or no posts exist')
TypeError: Invalid URL or no posts exist
```

**Comment by juanpabloaj** [comment]
in commit 550507fb8caacd10ea6da1ea2d675e7d6a700ea6
